language: java

skip_cleanup: true

before_deploy:
  - git config --local user.name "azryelryvel"
  - git config --local user.email "daryl@azry.net"
  - export TRAVIS_TAG="$TRAVIS_BUILD_NUMBER"
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $TOKEN
  file: "build/libs/jmxutils.jar"
